// Generated by gencpp from file coordinate_msgs/coordinate.msg
// DO NOT EDIT!


#ifndef COORDINATE_MSGS_MESSAGE_COORDINATE_H
#define COORDINATE_MSGS_MESSAGE_COORDINATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/PoseArray.h>

namespace coordinate_msgs
{
template <class ContainerAllocator>
struct coordinate_
{
  typedef coordinate_<ContainerAllocator> Type;

  coordinate_()
    : Header()
    , Pose()
    , PoseArray()  {
    }
  coordinate_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , Pose(_alloc)
    , PoseArray(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
  _Header_type Header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _Pose_type;
  _Pose_type Pose;

   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _PoseArray_type;
  _PoseArray_type PoseArray;





  typedef boost::shared_ptr< ::coordinate_msgs::coordinate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coordinate_msgs::coordinate_<ContainerAllocator> const> ConstPtr;

}; // struct coordinate_

typedef ::coordinate_msgs::coordinate_<std::allocator<void> > coordinate;

typedef boost::shared_ptr< ::coordinate_msgs::coordinate > coordinatePtr;
typedef boost::shared_ptr< ::coordinate_msgs::coordinate const> coordinateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coordinate_msgs::coordinate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coordinate_msgs::coordinate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::coordinate_msgs::coordinate_<ContainerAllocator1> & lhs, const ::coordinate_msgs::coordinate_<ContainerAllocator2> & rhs)
{
  return lhs.Header == rhs.Header &&
    lhs.Pose == rhs.Pose &&
    lhs.PoseArray == rhs.PoseArray;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::coordinate_msgs::coordinate_<ContainerAllocator1> & lhs, const ::coordinate_msgs::coordinate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace coordinate_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::coordinate_msgs::coordinate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coordinate_msgs::coordinate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coordinate_msgs::coordinate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coordinate_msgs::coordinate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coordinate_msgs::coordinate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coordinate_msgs::coordinate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coordinate_msgs::coordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81fd5275d7ab07817f427c0fbfe9e028";
  }

  static const char* value(const ::coordinate_msgs::coordinate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81fd5275d7ab0781ULL;
  static const uint64_t static_value2 = 0x7f427c0fbfe9e028ULL;
};

template<class ContainerAllocator>
struct DataType< ::coordinate_msgs::coordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coordinate_msgs/coordinate";
  }

  static const char* value(const ::coordinate_msgs::coordinate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coordinate_msgs::coordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header Header\n"
"geometry_msgs/Pose Pose\n"
"geometry_msgs/PoseArray PoseArray\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
;
  }

  static const char* value(const ::coordinate_msgs::coordinate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coordinate_msgs::coordinate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.Pose);
      stream.next(m.PoseArray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coordinate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coordinate_msgs::coordinate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coordinate_msgs::coordinate_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "Pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.Pose);
    s << indent << "PoseArray: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.PoseArray);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COORDINATE_MSGS_MESSAGE_COORDINATE_H
